sudo: required
services: 
  - docker


before_install:
  - docker build -t  tomaszpkaminski/docker-react -f Dockerfile.dev .

script:
  - docker run tomaszpkaminski/docker-react npm run test -- --coverage